require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GeocitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Geocity. As you add validations to Geocity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GeocitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all geocities as @geocities" do
      geocity = Geocity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:geocities).should eq([geocity])
    end
  end

  describe "GET show" do
    it "assigns the requested geocity as @geocity" do
      geocity = Geocity.create! valid_attributes
      get :show, {:id => geocity.to_param}, valid_session
      assigns(:geocity).should eq(geocity)
    end
  end

  describe "GET new" do
    it "assigns a new geocity as @geocity" do
      get :new, {}, valid_session
      assigns(:geocity).should be_a_new(Geocity)
    end
  end

  describe "GET edit" do
    it "assigns the requested geocity as @geocity" do
      geocity = Geocity.create! valid_attributes
      get :edit, {:id => geocity.to_param}, valid_session
      assigns(:geocity).should eq(geocity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Geocity" do
        expect {
          post :create, {:geocity => valid_attributes}, valid_session
        }.to change(Geocity, :count).by(1)
      end

      it "assigns a newly created geocity as @geocity" do
        post :create, {:geocity => valid_attributes}, valid_session
        assigns(:geocity).should be_a(Geocity)
        assigns(:geocity).should be_persisted
      end

      it "redirects to the created geocity" do
        post :create, {:geocity => valid_attributes}, valid_session
        response.should redirect_to(Geocity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved geocity as @geocity" do
        # Trigger the behavior that occurs when invalid params are submitted
        Geocity.any_instance.stub(:save).and_return(false)
        post :create, {:geocity => {  }}, valid_session
        assigns(:geocity).should be_a_new(Geocity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Geocity.any_instance.stub(:save).and_return(false)
        post :create, {:geocity => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested geocity" do
        geocity = Geocity.create! valid_attributes
        # Assuming there are no other geocities in the database, this
        # specifies that the Geocity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Geocity.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => geocity.to_param, :geocity => { "these" => "params" }}, valid_session
      end

      it "assigns the requested geocity as @geocity" do
        geocity = Geocity.create! valid_attributes
        put :update, {:id => geocity.to_param, :geocity => valid_attributes}, valid_session
        assigns(:geocity).should eq(geocity)
      end

      it "redirects to the geocity" do
        geocity = Geocity.create! valid_attributes
        put :update, {:id => geocity.to_param, :geocity => valid_attributes}, valid_session
        response.should redirect_to(geocity)
      end
    end

    describe "with invalid params" do
      it "assigns the geocity as @geocity" do
        geocity = Geocity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Geocity.any_instance.stub(:save).and_return(false)
        put :update, {:id => geocity.to_param, :geocity => {  }}, valid_session
        assigns(:geocity).should eq(geocity)
      end

      it "re-renders the 'edit' template" do
        geocity = Geocity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Geocity.any_instance.stub(:save).and_return(false)
        put :update, {:id => geocity.to_param, :geocity => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested geocity" do
      geocity = Geocity.create! valid_attributes
      expect {
        delete :destroy, {:id => geocity.to_param}, valid_session
      }.to change(Geocity, :count).by(-1)
    end

    it "redirects to the geocities list" do
      geocity = Geocity.create! valid_attributes
      delete :destroy, {:id => geocity.to_param}, valid_session
      response.should redirect_to(geocities_url)
    end
  end

end
