require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RaligionsController do

  # This should return the minimal set of attributes required to create a valid
  # Raligion. As you add validations to Raligion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RaligionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all raligions as @raligions" do
      raligion = Raligion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:raligions).should eq([raligion])
    end
  end

  describe "GET show" do
    it "assigns the requested raligion as @raligion" do
      raligion = Raligion.create! valid_attributes
      get :show, {:id => raligion.to_param}, valid_session
      assigns(:raligion).should eq(raligion)
    end
  end

  describe "GET new" do
    it "assigns a new raligion as @raligion" do
      get :new, {}, valid_session
      assigns(:raligion).should be_a_new(Raligion)
    end
  end

  describe "GET edit" do
    it "assigns the requested raligion as @raligion" do
      raligion = Raligion.create! valid_attributes
      get :edit, {:id => raligion.to_param}, valid_session
      assigns(:raligion).should eq(raligion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Raligion" do
        expect {
          post :create, {:raligion => valid_attributes}, valid_session
        }.to change(Raligion, :count).by(1)
      end

      it "assigns a newly created raligion as @raligion" do
        post :create, {:raligion => valid_attributes}, valid_session
        assigns(:raligion).should be_a(Raligion)
        assigns(:raligion).should be_persisted
      end

      it "redirects to the created raligion" do
        post :create, {:raligion => valid_attributes}, valid_session
        response.should redirect_to(Raligion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raligion as @raligion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raligion.any_instance.stub(:save).and_return(false)
        post :create, {:raligion => {  }}, valid_session
        assigns(:raligion).should be_a_new(Raligion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raligion.any_instance.stub(:save).and_return(false)
        post :create, {:raligion => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raligion" do
        raligion = Raligion.create! valid_attributes
        # Assuming there are no other raligions in the database, this
        # specifies that the Raligion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Raligion.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => raligion.to_param, :raligion => { "these" => "params" }}, valid_session
      end

      it "assigns the requested raligion as @raligion" do
        raligion = Raligion.create! valid_attributes
        put :update, {:id => raligion.to_param, :raligion => valid_attributes}, valid_session
        assigns(:raligion).should eq(raligion)
      end

      it "redirects to the raligion" do
        raligion = Raligion.create! valid_attributes
        put :update, {:id => raligion.to_param, :raligion => valid_attributes}, valid_session
        response.should redirect_to(raligion)
      end
    end

    describe "with invalid params" do
      it "assigns the raligion as @raligion" do
        raligion = Raligion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raligion.any_instance.stub(:save).and_return(false)
        put :update, {:id => raligion.to_param, :raligion => {  }}, valid_session
        assigns(:raligion).should eq(raligion)
      end

      it "re-renders the 'edit' template" do
        raligion = Raligion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raligion.any_instance.stub(:save).and_return(false)
        put :update, {:id => raligion.to_param, :raligion => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raligion" do
      raligion = Raligion.create! valid_attributes
      expect {
        delete :destroy, {:id => raligion.to_param}, valid_session
      }.to change(Raligion, :count).by(-1)
    end

    it "redirects to the raligions list" do
      raligion = Raligion.create! valid_attributes
      delete :destroy, {:id => raligion.to_param}, valid_session
      response.should redirect_to(raligions_url)
    end
  end

end
